sensor:

  - name: "Hours Since Last Blade Maintenance"
    unique_id: blade_hours_since_maintenance
    icon: mdi:timer-outline
    unit_of_measurement: "h"
    state: >
      {% set last_hours = states('input_number.blade_last_reset_hours') | float(0) %}
      {% set total_minutes = states('sensor.luba_vsdqbq84_total_time') | float(0) %}
      {% set total_hours = total_minutes / 60 %}
      {% if total_hours >= last_hours %}
        {{ (total_hours - last_hours) | round(1) }}
      {% else %}
        unknown
      {% endif %}
          
    - name: "Time Since Last Mow Main Area - 1"
      state: >
        {% set last_mow = state_attr('input_datetime.main_last_mow_1', 'timestamp') %}
        {% if last_mow %}
          {{ ((as_datetime(now()) - as_datetime(last_mow)).days) }} days
        {% else %}
          unknown
        {% endif %}

    - name: "Time Since Last Mow Main Area - 2"
      state: >
        {% set last_mow = state_attr('input_datetime.main_last_mow_2', 'timestamp') %}
        {% if last_mow %}
          {{ ((as_datetime(now()) - as_datetime(last_mow)).days) }} days
        {% else %}
          unknown
        {% endif %}

    - name: "Time Since Last Mow Main Area - 3"
      state: >
        {% set last_mow = state_attr('input_datetime.main_last_mow_3', 'timestamp') %}
        {% if last_mow %}
          {{ ((as_datetime(now()) - as_datetime(last_mow)).days) }} days
        {% else %}
          unknown
        {% endif %}

    - name: "Hours Since Last Blade Maintenance"
      unique_id: blade_hours_since_maintenance
      unit_of_measurement: "h"
      state: >
        {% set last_hours = states('input_number.blade_last_reset_hours') | float(0) %}
        {% set total_hours = states('sensor.luba_vsdqbq84_total_time') | float(0) %}
        {% if total_hours >= last_hours %}
          {{ (total_hours - last_hours) | round(1) }}
        {% else %}
          unknown
        {% endif %}
